name: pip_services4_grpc
version: "0.0.1"
description: This component library is a part of the [Pip.Services](https://github.com/pip-services/pip-services) project.It provides the following GRPC Communication components.
homepage: https://github.com/pip-services4/pip-services4-dart/tree/main/pip-services4-grpc-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pip_services4_commons: ^0.0.2
  pip_services4_components: ^0.0.1
  pip_services4_observability: ^0.0.1
  pip_services4_data: ^0.0.2
  pip_services4_rpc: ^0.0.2
  pip_services4_config: ^0.0.2
  grpc: ^3.0.2
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.17.12
  lints: ^2.1.1