# Start with the Dart image
FROM dart

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all dependencies
RUN dart pub get
RUN dart pub get --offline

# Specify the command from running tests
CMD ["/bin/sh", "./build.sh"]