name: pip_services4_commons
version: "0.0.1"
description: Common patterns for Pip.Services in Dart. This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project.
homepage: https://github.com/pip-services4/pip-services4-dart/pip-services4-commons-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^3.0.4
  analyzer: ^6.0.0

dev_dependencies:
  test: ^1.17.12