name: pip_services4_config
version: "0.0.2"
description: Config Components for Pip.Services in Dart. This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project.
homepage: https://github.com/pip-services4/pip-services4-dart/tree/main/pip-services4-config-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pip_services4_commons: ^0.0.2
  pip_services4_components: ^0.0.1
  pip_services4_expressions: ^0.0.1
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.17.12
  lints: ^2.1.1