FROM dart

# set working directory
WORKDIR /app

# copy all project
COPY . .

# Install all dependencies
RUN dart pub get
RUN dart pub get --offline

# Specify the command from running tests
CMD sleep 30 && dart pub run test