name: pip_services4_rabbitmq
version: "0.0.1"
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains RabbitMQ message queues
homepage: https://github.com/pip-services4/pip-services4-dart/tree/main/pip-services4-rabbitmq-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pip_services4_commons: ^0.0.2
  pip_services4_components: ^0.0.1
  pip_services4_config: ^0.0.2
  pip_services4_observability: ^0.0.1
  pip_services4_messaging: ^0.0.1
  dart_amqp: ^0.2.5
 
dev_dependencies:
  test: ^1.17.12
  lints: ^2.1.1  