name: pip_services4_expressions
version: "0.0.1"
description: This library is a part of the [Pip.Services](https://pipservices.org) polyglot microservices toolkit. It provides syntax and lexical analyzers and expression calculator optimized for repeated calculations.
homepage: https://github.com/pip-services4/pip-services4-dart/tree/main/pip-services4-expressions-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pip_services4_commons: ^0.0.2
  pip_services4_components: ^0.0.1

dev_dependencies:
  test: ^1.17.12
  lints: ^2.1.1